channel_targets:
  - tudat-team main
channel_sources:
  - tudat-team
  - conda-forge
  - defaults
boost_cpp:
  - 1.64
channels:
  sources: [tudat-team, conda-forge, defaults]
  targets:
    - [tudat-team, main]


