package:
  name: tudat-resources
  version: 1.0.1

source:
  git_url: https://github.com/tudat-team/tudat-resources.git
  git_rev: v1.0.1

requirements:
  build:
    # Tools required to build the package. These packages are run on the build
    # system and include things such as revision control systems (Git, SVN) make
    # tools (GNU make, Autotool, CMake) and compilers (real cross, pseudo-cross,
    # or native when not cross-compiling), and any source pre-processors.
    - cmake

about:
  home: http://tudat.tudelft.nl/
  license: BSD
  license_family: BSD
  summary: A curated database of resources to perform astrodynamics and space research
