{% set name = "tudat-resources" %}
  {% set version = "1.0.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/tudat-team/tudat-resources.git
  git_rev: {{ version }}

build:
  # A non-negative integer representing the build number of the package.
  #  Unlike the build string, the build_number is inspected by conda.
  #  Conda uses it to sort packages that have otherwise identical names
  #  and versions to determine the latest one. This is important because
  #  new builds that contain bug fixes for the way a package is built may be
  #  added to a repository.
  number: 1
  ignore_run_exports:
    - m2w64-gcc-libs  # [win]

requirements:
  build:
    # Tools required to build the package. These packages are run on the build
    # system and include things such as revision control systems (Git, SVN) make
    # tools (GNU make, Autotool, CMake) and compilers (real cross, pseudo-cross,
    # or native when not cross-compiling), and any source pre-processors.
    - {{ compiler('cxx') }}              # [not win]
    - {{ compiler('c') }}                # [not win]
    - {{ compiler('m2w64_c') }}         # [win]
    - m2w64-toolchain                   # [win]
#    - vs2017_{{ target_platform  }}      # [win]
    - cmake

test:
  requires:
    - cmake
  source_files:
    - test/test_binary
  commands:
    - cd ./test/test_binary
    - bash run_binary_test.sh

about:
  home: http://tudat.tudelft.nl/
  license: BSD
  license_family: BSD
  summary: A resource manager aimed towards astrodynamics and space research.

extra:
  recipe-maintainers:
    - ggarrett13


