package:
  name: tudat-resources
  version: 1.0.6

source:
  git_url: https://github.com/tudat-team/tudat-resources.git
  git_rev: 35f9f26b54cc8b8085754c6e0f6a73901ddeb215

build:
  # A non-negative integer representing the build number of the package.
  #  Unlike the build string, the build_number is inspected by conda.
  #  Conda uses it to sort packages that have otherwise identical names
  #  and versions to determine the latest one. This is important because
  #  new builds that contain bug fixes for the way a package is built may be
  #  added to a repository.
  number: 3

requirements:
  build:
    # Tools required to build the package. These packages are run on the build
    # system and include things such as revision control systems (Git, SVN) make
    # tools (GNU make, Autotool, CMake) and compilers (real cross, pseudo-cross,
    # or native when not cross-compiling), and any source pre-processors.
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('c') }}              # [not win]
    - cmake

test:
  source_files:
    - test/test_binary
  commands:
    - cd ./test/test_binary
    - bash run_binary_test.sh

about:
  home: http://tudat.tudelft.nl/
  license: BSD
  license_family: BSD
  summary: A curated database of resources to perform astrodynamics and space research.
