package:
  name: tudat-resources
  version: 1.0.5

source:
  git_url: https://github.com/tudat-team/tudat-resources.git
  git_rev: 6cdabd32e8397f2e3eea8a67d16b37f7b41d4863

requirements:
  build:
    # Tools required to build the package. These packages are run on the build
    # system and include things such as revision control systems (Git, SVN) make
    # tools (GNU make, Autotool, CMake) and compilers (real cross, pseudo-cross,
    # or native when not cross-compiling), and any source pre-processors.
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('c') }}              # [not win]
    - boost-cpp
    - cmake


test:
  downstreams:
    - tudat

about:
  home: http://tudat.tudelft.nl/
  license: BSD
  license_family: BSD
  summary: A curated database of resources to perform astrodynamics and space research
